version: "3.2"
services:
  web:
    build: .
    ports:
      - "5000:80"
    env_file:
      - secret.env
    volumes:
      - $PWD:/app
  redis:
    image: "redis:alpine"
    command: redis-server #--requirepass
    ports:
     - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
